name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      env: 
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      run: |
        echo "$PINECONE_API_KEY"
        pip install pytest
        pip install pytest-cov
        pip install coverage
        pip install pinecone-client
        pip install -r requirements.txt
        coverage run -m unittest
        coverage run -m pytest tests/test.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODE_COV }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true
