name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      env: 
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pip install pytest
        pip install pytest-cov
        pip install coverage
        pip install pinecone-client
        pip install pinecone-cli
        pip install -r requirements.txt
        echo "Starting coverage tests"
        pytest  --cov=./ --cov-report=xml tests/test.py -s
        # coverage run -m pytest tests/test.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env: 
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        env_vars: OS,PYTHON,OPENAI_API_KEY
        files: ./coverage.xml,!./cache
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
